[package]
name = "k_means"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
rabitq = { path = "../rabitq" }
simd = { path = "../simd" }

rand.workspace = true
rand_distr = "0.5.1"
rayon = "1.11.0"

[lints]
workspace = true
